name: Feature Request
description: Suggest a new feature or enhancement for Eclipse Shield
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for suggesting a feature! ✨
        
        We appreciate your ideas for improving Eclipse Shield. Please provide as much detail as possible to help us understand your suggestion.

  - type: checkboxes
    id: preliminary-checks
    attributes:
      label: Preliminary Checks
      description: Please confirm you have completed these steps
      options:
        - label: I have searched existing issues and this feature hasn't been requested
          required: true
        - label: I have reviewed the project roadmap
          required: true
        - label: This feature aligns with Eclipse Shield's mission of productivity and security
          required: true

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: What category does this feature belong to?
      options:
        - AI/Machine Learning improvements
        - Security enhancements
        - Browser extension functionality
        - API improvements
        - User interface/experience
        - Performance optimization
        - Configuration options
        - Monitoring and analytics
        - Integration with external services
        - Documentation improvements
        - Developer tools
        - Other
    validations:
      required: true

  - type: textarea
    id: feature-summary
    attributes:
      label: Feature Summary
      description: A brief, one-sentence description of the feature
      placeholder: Add support for Firefox browser extension
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What gap does it fill?
      placeholder: |
        Currently, Eclipse Shield only supports Chrome and Opera browsers. Firefox users cannot benefit from the productivity analysis and website blocking features.
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Detailed description of the feature you'd like to see implemented
      placeholder: |
        Implement a Firefox WebExtension version of the browser extension that:
        - Uses the same API endpoints as Chrome/Opera versions
        - Maintains feature parity with existing extensions
        - Follows Firefox WebExtension standards
    validations:
      required: true

  - type: textarea
    id: user-benefits
    attributes:
      label: User Benefits
      description: How will this feature benefit users?
      placeholder: |
        - Firefox users can access Eclipse Shield's productivity features
        - Increased user base and broader browser support
        - Consistent experience across different browsers
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: Primary User Type
      description: Who would primarily benefit from this feature?
      options:
        - End users (people using Eclipse Shield for productivity)
        - Developers (contributing to or integrating with Eclipse Shield)
        - System administrators (deploying/managing Eclipse Shield)
        - Security professionals (analyzing or hardening Eclipse Shield)
        - All users
    validations:
      required: true

  - type: textarea
    id: security-considerations
    attributes:
      label: Security Considerations
      description: |
        How might this feature impact security? Consider:
        - New attack vectors
        - Data privacy implications
        - Authentication/authorization changes
        - Input validation requirements
      placeholder: |
        Firefox extension would need:
        - Same input validation as existing extensions
        - Secure communication with backend API
        - Proper permission handling for Firefox's security model
    validations:
      required: true

  - type: textarea
    id: implementation-ideas
    attributes:
      label: Implementation Ideas
      description: |
        Do you have ideas about how this could be implemented? (Technical suggestions welcome but not required)
      placeholder: |
        - Use WebExtension Manifest V2/V3 for Firefox compatibility
        - Share common JavaScript modules between Chrome and Firefox versions
        - Adapt existing background scripts to Firefox's extension architecture
    validations:
      required: false

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives Considered
      description: What other solutions have you considered?
      placeholder: |
        - Using a standalone desktop application instead of browser extension
        - Browser-agnostic web-based solution
        - Third-party productivity tools
    validations:
      required: false

  - type: dropdown
    id: complexity-estimate
    attributes:
      label: Complexity Estimate
      description: How complex do you think this feature would be to implement?
      options:
        - Simple - Small code change or configuration
        - Medium - Moderate development effort
        - Complex - Significant development effort
        - Major - Large architectural changes required
        - Unknown - Not sure about complexity
    validations:
      required: true

  - type: dropdown
    id: priority-level
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Nice to have - Would be cool but not essential
        - Important - Would significantly improve experience
        - Critical - Needed for basic functionality
        - Blocking - Cannot use Eclipse Shield without this
    validations:
      required: true

  - type: input
    id: timeline
    attributes:
      label: Desired Timeline
      description: When would you like to see this feature? (No guarantees, just helps with planning)
      placeholder: e.g., "Next release", "Within 6 months", "No rush"
    validations:
      required: false

  - type: textarea
    id: related-issues
    attributes:
      label: Related Issues/Discussions
      description: Link to any related issues, discussions, or external resources
      placeholder: |
        - Related to issue #123
        - Discussed in community chat: [link]
        - Similar to feature in other tools: [link]
    validations:
      required: false

  - type: checkboxes
    id: contribution-willingness
    attributes:
      label: Contribution
      description: Are you interested in contributing to this feature?
      options:
        - label: I'm willing to help implement this feature
        - label: I can help with testing this feature
        - label: I can help with documentation for this feature
        - label: I can provide design/UX input for this feature

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Any other context, mockups, examples, or references that would help explain this feature
        - Screenshots or mockups
        - Examples from other applications
        - Research or supporting data
    validations:
      required: false

  - type: checkboxes
    id: feature-scope
    attributes:
      label: Feature Scope
      description: Please indicate which components this feature would affect
      options:
        - label: Browser Extension
        - label: Backend API
        - label: AI/ML Components
        - label: Security Systems
        - label: User Interface
        - label: Configuration System
        - label: Documentation
        - label: Deployment/Infrastructure
